### ISSUE TITLE
DriveShare Graph Summary Not Working

### ISSUE THREAD

**Issue by super3** [Storj/driveshare-graph#2]
See http://pastebin.com/eeuzANft. Has stopped producing entries since Jan 2nd.

**Comment by super3** [comment]
@subwolf @jaylagorio Moved this issue here

**Comment by jaylagorio** [comment]
Great, thanks @super3!

**Comment by super3** [comment]
@Andrew-Kim @frdwrd Seems to have stopped working on January 2nd. See this sample address: http://graph.driveshare.org/api/summary/15tEiA7mTmEeY7APUfmpYwvsWdSBuDghfh

**Comment by subwolf** [comment]
Has anything in the dataserv json output changed that would upset the scraper?

**Comment by super3** [comment]
Doubt it. We haven't made any changes to the dataserv json at all for quite a long time.

**Comment by subwolf** [comment]
Good news, http://graph.driveshare.org/json is up to date at least, though the date field doesn't translate.

**Comment by jaylagorio** [comment]
I think the date translates fine:

{"total_TB": 2140.61, "total_farmers": 827, "time": {"$date": 1453809724245}}
{"total_TB": 2280.22, "total_farmers": 913, "time": {"$date": 1453896215527}}

And via http://www.epochconverter.com/:
1453809724245 => GMT: Tue, 26 Jan 2016 12:02:04 GMT
1453896215527 => GMT: Wed, 27 Jan 2016 12:03:35 GMT

Or is that wrong but conveniently worked out?

**Comment by subwolf** [comment]
Tracked the issue to https://stackoverflow.com/questions/10570635/scrapy-importerror-no-module-named-items#10570868 - been trying to fix this but bet you or @F483 can sort it in minutes?

```
subwolf@subwolf-desktop /data/driveshare-graph/scrapers $ ./scrapeAPI.sh 
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 142, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 209, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 115, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 296, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spiderloader.py", line 30, in from_settings
    return cls(settings)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spiderloader.py", line 21, in __init__
    for module in walk_modules(name):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/misc.py", line 71, in walk_modules
    submod = import_module(fullpath)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/driveshare-graph/scrapers/farmerSpider/farmerSpider/spiders/farmers_spider.py", line 2, in <module>
    from farmers_spider.items import spiderItem
ImportError: No module named items
2016-02-06 14:40:53 [scrapy] INFO: Scrapy 1.0.5 started (bot: totalStorage)
```

So the first bot is not run, but the second does.

**Comment by jaylagorio** [comment]
@super3 Any movement on this? My basic motivation is to create graphs based on the data but if there's another URL that returns an image of a graph or SVG output for an individual farmer (like the overall graphs on the http://graph.driveshare.org/ base page) that would solve my root problem too.

**Comment by super3** [comment]
@subwolf what version of python are you running it on?
@jaylagorio Is this something you can create from dataserv directly outside of driveshare-graph?

**Comment by jaylagorio** [comment]
@shawn No, dataserv only provides real-time data on addresses connected to the network, it doesn't appear to store past statistics like driveshare-graph does. I can take those stats to make a visual graph but I would need a direct connection to dataserve and to start saving connection data myself. Is there a way to access the underlying data that driveshare-graph generates its statistics from? If I could access that I could generate the per-day up time tracking stats myself. That would still be harder on the server than fixing this and doing one query per address though.

**Comment by super3** [comment]
@jaylagorio This issue is in a bit of a holding pattern because we are not sure what we are going to do with dataserv. Most likely it will be completely replaced as Test Group C and MetaDisk comes on line.

**Comment by jaylagorio** [comment]
That makes sense. Will TGC or MetaDisk have APIs that will let you query what the network thinks about farmer performance data, either for everyone publicly or the addresses a farmer owns? For good measure that might also be a good place to put IP addresses of farmers.

**Comment by super3** [comment]
Not initially, but we we build that. IP addresses will be obfuscated.

On Sat, Mar 5, 2016 at 3:36 PM, jaylagorio notifications@github.com wrote:

> That makes sense. Will TGC or MetaDisk have APIs that will let you query
> what the network thinks about farmer performance data, either for everyone
> publicly or the addresses a farmer owns? For good measure that might also
> be a good place to put IP addresses of farmers.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Storj/driveshare-graph/issues/2#issuecomment-192729903
> .

## 

Shawn Wilkinson
Lead Developer and Founder | storj.io
me@super3.org | super3.org

**Comment by jaylagorio** [comment]
Sounds like a plan! Were you thinking leaving the first three octets of the IP address in the clear and obfuscating the fourth? I think when we were on this topic in another repo we didn't care if the IP address was out in the open because of the P2P nature of the system but I don't really have an opinion on the matter either way.

**Comment by super3** [comment]
Best be on the safe side.

Shawn

On Sat, Mar 5, 2016 at 6:19 PM, jaylagorio notifications@github.com wrote:

> Sounds like a plan! Were you thinking leaving the first three octets of
> the IP address in the clear and obfuscating the fourth? I think when we
> were on this topic in another repo we didn't care if the IP address was out
> in the open because of the P2P nature of the system but I don't really have
> an opinion on the matter either way.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Storj/driveshare-graph/issues/2#issuecomment-192758318
> .

## 

Shawn Wilkinson
Lead Developer and Founder | storj.io
me@super3.org | super3.org

**Comment by subwolf** [comment]
If API details could be published before TGC goes live so we have a day or
two to implement them, it would be a big help. We only need the json links
to scrape from, not a parsed output like graph is supposed to provide.

**Comment by jaylagorio** [comment]
That's a wonderful idea!

**Comment by super3** [comment]
Probably going to be a few weeks before we code up another system, but I
can totally share you the schema before hand. Will be my priority next
week.

On Sun, Mar 6, 2016 at 10:30 AM, jaylagorio notifications@github.com
wrote:

> That's a wonderful idea!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Storj/driveshare-graph/issues/2#issuecomment-192914371
> .

## 

Shawn Wilkinson
Lead Developer and Founder | storj.io
me@super3.org | super3.org
